name: image_analysis_venv
dependencies:
  - python=3.7
  - numpy=1.20.*
  - matplotlib=3.4.2
  - pip
  - pip:
    - PyQt5==5.15.4
    - pyqtgraph==0.12.1
    - rsMap3D==1.2.1
    - scipy==1.6.3
    - setuptools==56.2.0
    - tifffile==2021.4.8
    - vtk==9.0.3
    - xrayutilities==1.7.1
